module WillPaginate
  # PaginatedCollection is a proxy to the original array of
  # records. It is generated by AR::Base#paginate methods.
  #
  class PaginatedCollection
    attr_reader :current_page, :per_page, :entries
    attr_accessor :total_entries

    def initialize(entries, page, per_page, total)
      @entries       = entries
      @current_page  = page
      @per_page      = per_page
      @total_entries = total
      @total_pages   = (@total_entries / @per_page.to_f).ceil
    end

    def page_count
      @total_pages
    end

    include Enumerable

    def each &block
      @entries.each &block
    end

    def to_a
      @entries
    end
    
  protected

    # delegate missing stuff to the collection array
    def method_missing(method, *args, &block)
      @entries.send method, *args, &block
    end
  end
end
