# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{tism-will_paginate}
  s.version = "2.3.16"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Mislav Marohni\304\207", "PJ Hyett"]
  s.date = %q{2011-03-16}
  s.description = %q{Relase to use https://github.com/tism/will_paginate/commit/adea61b139285357d72ae61e97bb49d709c20bb9}
  s.email = %q{mislav.marohnic@gmail.com}
  s.extra_rdoc_files = [
    "CHANGELOG.rdoc",
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "lib/will_paginate.rb",
    "lib/will_paginate/array.rb",
    "lib/will_paginate/collection.rb",
    "lib/will_paginate/core_ext.rb",
    "lib/will_paginate/finder.rb",
    "lib/will_paginate/named_scope.rb",
    "lib/will_paginate/named_scope_patch.rb",
    "lib/will_paginate/version.rb",
    "lib/will_paginate/view_helpers.rb",
    "test/boot.rb",
    "test/collection_test.rb",
    "test/console",
    "test/database.yml",
    "test/finder_test.rb",
    "test/fixtures/admin.rb",
    "test/fixtures/developer.rb",
    "test/fixtures/developers_projects.yml",
    "test/fixtures/project.rb",
    "test/fixtures/projects.yml",
    "test/fixtures/replies.yml",
    "test/fixtures/reply.rb",
    "test/fixtures/schema.rb",
    "test/fixtures/topic.rb",
    "test/fixtures/topics.yml",
    "test/fixtures/user.rb",
    "test/fixtures/users.yml",
    "test/helper.rb",
    "test/lib/activerecord_test_case.rb",
    "test/lib/activerecord_test_connector.rb",
    "test/lib/load_fixtures.rb",
    "test/lib/view_test_process.rb",
    "test/tasks.rake",
    "test/view_test.rb"
  ]
  s.homepage = %q{http://github.com/mislav/will_paginate/wikis}
  s.rdoc_options = ["--main", "README.rdoc", "--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.4.2}
  s.summary = %q{Pagination for Rails}
  s.test_files = [
    "test/boot.rb",
    "test/collection_test.rb",
    "test/finder_test.rb",
    "test/fixtures/admin.rb",
    "test/fixtures/developer.rb",
    "test/fixtures/project.rb",
    "test/fixtures/reply.rb",
    "test/fixtures/schema.rb",
    "test/fixtures/topic.rb",
    "test/fixtures/user.rb",
    "test/helper.rb",
    "test/lib/activerecord_test_case.rb",
    "test/lib/activerecord_test_connector.rb",
    "test/lib/load_fixtures.rb",
    "test/lib/view_test_process.rb",
    "test/view_test.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

