#!/bin/bash
set -e

brew bundle

while [ ! -e /tmp/mysql.sock ]; do
  echo "Waiting for /tmp/mysql.sock ..." >&2
  sleep 1
done

mysql -u root -e 'CREATE DATABASE IF NOT EXISTS will_paginate;'
psql --dbname will_paginate -c '' 2>/dev/null || createdb will_paginate

bundle install --path "${PWD}/vendor/bundle"
